# Generated by Django 5.0.6 on 2024-06-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobilePhone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("imei", models.CharField(max_length=15, unique=True)),
                ("model", models.CharField(max_length=20, null=True)),
                ("color", models.CharField(max_length=20, null=True)),
                ("price", models.FloatField(null=True)),
                ("weight", models.FloatField(null=True)),
                ("size", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RepairMan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("job", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RepairManager",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RepairProject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("projectName", models.CharField(max_length=20)),
                ("laborCost", models.FloatField()),
                ("materialCost", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceAdvisor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10, null=True)),
                ("birthday", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RepairCommission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("repairType", models.CharField(default="common", max_length=20)),
                ("faultInfo", models.CharField(max_length=100)),
                ("materialCost", models.FloatField(default=0)),
                ("laborCost", models.FloatField(default=0)),
                ("totalCost", models.FloatField(default=0)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("isCarried", models.BooleanField(default=False)),
                ("isFinished", models.BooleanField(default=False)),
                ("isPaid", models.BooleanField(default=False)),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mmm.mobilephone",
                    ),
                ),
                (
                    "serviceAdvisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mmm.serviceadvisor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mmm.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepairOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project", models.CharField(max_length=20)),
                ("isFinished", models.BooleanField(default=False)),
                (
                    "repairCommission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mmm.repaircommission",
                    ),
                ),
                (
                    "repairMan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mmm.repairman"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPhones",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mmm.mobilephone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mmm.user"
                    ),
                ),
            ],
        ),
    ]
